### ISSUE TITLE
Cannot find module 'virtual:pwa-info' or its corresponding type declarations.

### ISSUE THREAD

**Issue by RectoVersoDev** [vite-pwa/astro#33]
Hello,

I'm following the [Prompt for Update PWA Example](https://github.com/vite-pwa/astro/tree/main/examples/pwa-prompt) 

Already done [this](https://vite-pwa-org.netlify.app/frameworks/#accessing-pwa-info) but I can't find a way to disable TS2307 error

**tsconfig.json:**
```
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "types": [
      "astro/client",
      "vite-plugin-pwa/info",
      "vite-plugin-pwa/vanillajs"
    ],
  }
}
``` 
=> I got error here : `Cannot find type definition file for 'vite-plugin-pwa/info'. The file is in the program because: Entry point of type library 'vite-plugin-pwa/info' specified in compilerOptions`

**env.d.ts:**
```typescript
/// <reference types="astro/client" />
/// <reference types="vite-plugin-pwa/info" />
/// <reference types="vite-plugin-pwa/vanillajs" />
``` 

**package.json:**
```
{
  "name": "tarifs-besancon",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@1055/ui": "workspace:^1.0.0",
    "@astrojs/check": "^0.3.2",
    "astro": "^4.0.4",
    "sharp": "^0.33.0",
    "typescript": "^5.3.3"
  },
  "devDependencies": {
    "@vite-pwa/astro": "^0.2.0",
    "workbox-window": "^7.0.0"
  }
}
``` 

Everywhere I try to import `virtual:pwa-info` or `virtual:pwa-register` I got the TS2307 error

There nothing specific to Astro for type declaration in the docs so I don't know what to do

**Comment by userquin** [comment]
what package manager are you using? try installing `vite-plugin-pwa` as dev dependency

**Comment by RectoVersoDev** [comment]
pnpm ! I'll try this ✅ I'll let you know

**Comment by RectoVersoDev** [comment]
Here is a [really basic CodeSandbox](https://codesandbox.io/p/github/RectoVersoDev/astro-pwa-test/master?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq58a4or00062a66smbkzcm5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq58a4or00022a66nwph0369%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq58a4or00042a66ip0i4mcp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq58a4or00052a66gljga1io%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq58a4or00022a66nwph0369%2522%253A%257B%2522id%2522%253A%2522clq58a4or00022a66nwph0369%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq58a4or00052a66gljga1io%2522%253A%257B%2522id%2522%253A%2522clq58a4or00052a66gljga1io%2522%252C%2522activeTabId%2522%253A%2522clq58egw100t72a66hssvhdnr%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A4321%252C%2522id%2522%253A%2522clq58egw100t72a66hssvhdnr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clq58a4or00042a66ip0i4mcp%2522%253A%257B%2522id%2522%253A%2522clq58a4or00042a66ip0i4mcp%2522%252C%2522activeTabId%2522%253A%2522clq58a6th007t2a66ks0wi99x%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq58a4or00032a663xj84k7b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clq58a4ed000negjs4snrbaq3%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clq58a6th007t2a66ks0wi99x%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clq58avcw00cv2a66udi2im4o%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) where we can see the error :

**Comment by userquin** [comment]
it seems a problem with pnpm and `shamefully-hoist` and/or installing peer dependencies...

**Comment by userquin** [comment]
can you try adding `"typescript": "^5.4.2"` to your dev dependencies and move all deps to dev dependecies in the repo/codesanbox reproduction (also update to latest Astro and "vite-plugin-pwa": "^0.19.4" as dev dependency)?

Running `pnpm astro check` seems to be fine now:

![imagen](https://github.com/vite-pwa/astro/assets/6311119/f289e88c-8566-49f1-952f-4406c46b11ba)


![imagen](https://github.com/vite-pwa/astro/assets/6311119/137d6421-4058-4bf8-8a77-c3f196e21b59)
