### ISSUE TITLE
Mutilanguage support

### ISSUE THREAD

**Issue by spokospace** [vite-pwa/astro#36]
Hello, thx for this PWA integration, it's great!

BTW. I have one issue with config second language. I have a page like mydomain.com and mydomain.com/pl/ with static pages generated by Astro.

It will be great to configure it like method 2 here:
https://dev.to/progressier/how-to-translate-a-pwa-app-manifest-2e7i

with  Accept-Language, what do you think?

Or it will be better to make some workaround to detect system language and switch?

**Comment by userquin** [comment]
@spokospace 

This astro integration module is for build time not for runtime; the approach in linked blog is just one way to detect locales (on first request), you can also use a cookie or client side logic.

You can configure `manifest: false` in your PWA configuration options adding the required logic to generate and detect/configured the web manifest file properly. With previous manifest option set to false, the PWA plugin will not generate the web manifest.

You can check for example elk.zone GH repo where we have static manifests per locale and theme color variants: check [pwa module](https://github.com/elk-zone/elk/tree/main/modules/pwa) (check i18n module), we added the required logic to generate the web manifest variants.
