### ISSUE TITLE
Cannot find module 'virtual:pwa-assets/head' or its corresponding type declarations.

### ISSUE THREAD

**Issue by zanhk** [vite-pwa/astro#40]
Hi,

I tried downloading the new added example [pwa-simple-assets-generator](https://github.com/vite-pwa/astro/tree/main/examples/pwa-simple-assets-generator) 

and I got the following error

"Cannot find module 'virtual:pwa-assets/head' or its corresponding type declarations."

on the `DefaultLayout.astro` file

https://codesandbox.io/p/github/zanhk/astro-pwa-simple-assets-generator

Am i missing something?

also i think the example is missing the package dependency

"@vite-pwa/assets-generator" 

as the terminal give the error

```
WARNING: you must install the following dev dependencies to use the PWA assets generator:
- "@vite-pwa/assets-generator"
- "sharp" (should be installed when installing @vite-pwa/assets-generator)
- "sharp-ico" (should be installed when installing @vite-pwa/assets-generator)
```

---

Thanks

**Comment by userquin** [comment]
You should add `vite-plugin-pwa/pwa-assets`  in your tsconfig compiler options types (`vite-plugin-pwa/head` doesn't exist):

![imagen](https://github.com/vite-pwa/astro/assets/6311119/a7a9ef70-5000-4b1a-98d5-52dda4cd81c5)

**Comment by userquin** [comment]
It is documented here: https://vite-pwa-org.netlify.app/assets-generator/integrations.html#new-virtual-modules

**Comment by zanhk** [comment]
ok Thanks
