### ISSUE TITLE
Wrong environment prefix. It should be `PUBLIC_` instead of `VITE_`

### ISSUE THREAD

**Issue by Eptagone** [vite-pwa/astro#42]
If you have client environment variables which should be included in the client side scripts, in Astro projects, they should have the prefix `PUBLIC_` but if you want to include them in a custom service worker, it won't work because VitePWA is ignoring them.
That's because VitePWA is expecting variables with the prefix `VITE_`. 

The default value for the environment prefix in Vite is [VITE_](https://vitejs.dev/config/shared-options.html#envprefix) but in Astro that prefix is [PUBLIC_](https://docs.astro.build/en/guides/environment-variables/) instead.

**Comment by userquin** [comment]
Read the astro docs, the env variables will not be loaded from .env files, you need to use vite .env variables.

**Comment by userquin** [comment]
can you try changing the vite entry in your astro config file?

```ts
vite: {
  envPrefix: 'PUBLIC_'
}
```

**Comment by userquin** [comment]
FYI: Astro configuring `envPrefix` properly:

![imagen](https://github.com/vite-pwa/astro/assets/6311119/1a182520-8a5a-4ef0-8bfd-b2b8d6393c54)

**Comment by userquin** [comment]
You cannot access in the client to non `PUBLIC_` env variables:

![imagen](https://github.com/vite-pwa/astro/assets/6311119/f7b9de19-36eb-4fa5-936b-a6ff493e4810)

**Comment by userquin** [comment]
can you provide a minimal repo with the custom sw?

**Comment by Eptagone** [comment]
> can you provide a minimal repo with the custom sw?

Here: https://github.com/Eptagone/astro-vitepwa-envprefix-test

I also discovered a strange thing. The `PUBLIC_` are correctly included in development mode. They are only ignored in production (build).

**Comment by userquin** [comment]
oh wait, you're using custom sw, maybe we need to change the astro pwa integration...

**Comment by userquin** [comment]
Local test seems to work, rn only `PUBLIC_` working, we need to add the array to make it work with `PUBLIC_` and `VITE_`.

Ater adding `.env` and running build with the new vite plugin pwa (PR and release 0.19.5 in a few minutes with pwa astro):

![imagen](https://github.com/vite-pwa/astro/assets/6311119/dc6d4ee4-6221-4d1b-8d13-2e509b677d3f)

**Comment by userquin** [comment]
With both entries also working:

![imagen](https://github.com/vite-pwa/astro/assets/6311119/0dc82dce-ff48-4058-9886-07cf5b9fb9a8)

**Comment by userquin** [comment]
tree shaking also working... nice

**Comment by userquin** [comment]
@Eptagone relased 0.3.1 version, should be fixed now

**Comment by Eptagone** [comment]
I can confirm that it's working now. Thank very much!
