### ISSUE TITLE
Can I avoid having my inline script affected by registerSW?

### ISSUE THREAD

**Issue by Zhengqbbb** [vite-pwa/astro#48]
After using `<script src="/src/pwa.ts"></script>` in the `<head>` section, my inline script, which contains essential handling for the page, is affected. 

I'm wondering if there's a way to handle this situation so that the SW file can load independently.

## Reproduce

https://stackblitz.com/edit/github-ccfwpe?file=src%2Flayouts%2FDefaultLayout.astro

https://github.com/vite-pwa/astro/assets/40693636/b86afaab-708a-45d6-a3c9-8fb55008ebaa

**Comment by userquin** [comment]
check your `DefaultLayout.astro`, it is importing `/src/main.ts` and you have 5 `console.log(1)` there

**Comment by Zhengqbbb** [comment]
The console.log is actually a placeholder for my main logic. What I mean is that if the logic is small enough, it can be inlined. However, if src/pwa is added, it will be bundled into a separate JS file, no matter how small it is.

**Comment by Zhengqbbb** [comment]
> Since Astro will not inject any script in your application when using Astro components

https://vite-pwa-org.netlify.app/frameworks/astro#importing-virtual-modules

BTW. When using [astro/prefetch](https://github.com/withastro/astro/blob/main/packages/astro/src/prefetch/vite-plugin-prefetch.ts), I noticed that they produce page.js as a script to load after bundling. Could it be that they already support inject?
 🤔

**Comment by userquin** [comment]
We cannot do anything about inlining here, ask in Astro repo

**Comment by userquin** [comment]
Try adding pwa logic inside main.ts

**Comment by Zhengqbbb** [comment]
> Try adding pwa logic inside main.ts (maybe using dynamic import)

I have tried... It was painful.

**Comment by userquin** [comment]
```ts
import('virtual:pwa-register').then(({ registerSW }) => {
  registerSW({
    immediate: true,
    onRegisteredSW(swScriptUrl) {
      // eslint-disable-next-line no-console
      console.log('SW registered: ', swScriptUrl)
    },
    onOfflineReady() {
      // eslint-disable-next-line no-console
      console.log('PWA application ready to work offline')
    }
  })
})
```

**Comment by Zhengqbbb** [comment]
I'm sorry for taking up your time. Both methods involve dependencies, and the code will be bundled regardless of its size. 
It looks like I'll need to use dual packaging and combine it with `is:inline` to handle it directly. 🙁 
After Astro is:line adding it,user has to handle it by himself, so bad.
